# Generated by Django 6.0.3 on 2026-03-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='admin_reply',
            field=models.TextField(blank=True, help_text='Phản hồi của Admin', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
